[@ww.radio label="Choose registry type" name="registryType" listKey="key" listValue="value" toggle="true" list=registryMap /]
[@ui.bambooSection dependsOn="registryType" showOn="custom"]
	[@ww.textfield label="Registry URL" name="customRegistryURL" required="false"/]
	[@ww.textfield label="Registry Username" name="customRegistryUsername" required="false"/]
	[@ww.password label="Registry Password" name="customRegistryPassword" showPassword="true" required="false"/]
[/@ui.bambooSection]
[@ww.textfield label="Repository" name="repository" required="true"/]
[@ww.textfield label="Tag" name="tag" required="true"/]
[@ww.checkbox label="Scan Layers" name="scanLayers" toggle="true" required="false"/]
[@ww.textfield label="High vulnerabilities to fail" name="highVul" required="false"/]
[@ww.textfield label="Medium vulnerabilities to fail" name="mediumVul" required="false"/]