name: Run NVSHAS-8797
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Scan Remote Image
        id: my_custom_scan
        uses: neuvector/scan-action@NVSHAS-8797-improve-set-output
        with:
          image-registry: https://registry.hub.docker.com
          image-registry-username: songlongtj
          image-registry-password: neuvector
          image-repository: songlongtj/alpine
          image-tag: "3.10"
          min-high-cves-to-fail: "5"
          min-medium-cves-to-fail: "5"
          output: json
          cve-names-to-exempt: "CVE-2021-23840,CVE-2020-1971"
      - name: Use Scan Results
        run: |
          echo "Vulnerability count: ${{ steps.my_custom_scan.outputs.vulnerability_count }}"
